### ISSUE TITLE
Fix error in SDDS writing

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/sdds#29]
Release `0.2` deployed all changes made since August 9, 2019. This means all commits from fca0994 to b0ee5b9 included.

Testing in `omc3` started breaking after using this new release, as can be seen [here](https://github.com/pylhc/omc3/pull/243/checks?check_run_id=1230749900).

The reading does not seem to pose an issue.
However, reading the result of a tbt conversion fails, encountering an `invalid start byte`, which indicates writing was wrong.

These tests in `omc3` fail starting with `sdds`'s commit 5d2a0d0, which is change made to writing behavior.

Should aim to fix this asap, add proper testing, and release `0.2.1`.

**Comment by lmalina** [comment]
Not a bug.

**Comment by fsoubelet** [comment]
(see https://github.com/pylhc/omc3/issues/244, the fault is in omc3)
