### ISSUE TITLE
encounter errors with sdds.read('file.sdds')

### ISSUE THREAD

**Issue by tiansk** [pylhc/sdds#4]
I want to use the sdds module to process the output data of ELEGANT,but when I used sdds.read(),it turns out errors.I'm a beginner in PYTHON,could anybody sent me a example script to show how to use sdds module. 
Email:tiansk@ihep.ac.cn

++++++++++++++++++++++
import sdds
import os

os.chdir(r'D:\IHEPBox\elegantExamples\PAR\twissCalculation')
sdds_data = sdds.read('parTwiss.twi')
++++++++++++++++++++++++++

I use the commands shown above to load the twiss file(a sdds file),but it turns errors like this:
### 
Traceback (most recent call last):
  File "C:\Users\Saike Tian\Desktop\1111111111111111111111111.py", line 5, in <module>
    sdds_data = sdds.read('parTwiss.twi')
  File "E:\ProgramData\Anaconda3\lib\site-packages\sdds\reader.py", line 25, in read_sdds
    version, definition_list, description, data = _read_header(inbytes)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sdds\reader.py", line 43, in _read_header
    def_dict: Dict[str, str] = _get_def_as_dict(word_gen)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sdds\reader.py", line 181, in _get_def_as_dict
    [assign.split("=") for assign in parts]}
  File "E:\ProgramData\Anaconda3\lib\site-packages\sdds\reader.py", line 180, in <dictcomp>
    return {key.strip(): value.strip() for (key, value) in
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by JoschD** [comment]
Hey Saike Tian,
your usage seems fine (it's that easy), so the problem seems to be with the header of the file.
Could you attach the file, please?

Bests

**Comment by JoschD** [comment]
From the ELEGANT manual (https://ops.aps.anl.gov/manuals/elegant_latest/elegantsu75.html#x83-820007.65) it seems that the tags are `&twiss_output`, 
while the current code only allows for `&description`. This is an error in our code, as we missed the line:

> Note: In many cases it is best to use a string parameter for descriptive text instead of the description 
command. The reason is that the Toolkit programs will allow manipulation of a string parameter.

in https://ops.aps.anl.gov/manuals/SDDStoolkit/SDDStoolkitsu2.html

There might also be a problem with the trailing ";".

**Comment by JoschD** [comment]
Closing this due as it is not needed anymore. And also as there is most likely a layer missing between the ELEGANT-Files and proper SDDS format.
