### ISSUE TITLE
[Bug]: Type Hints empty for derived class

### ISSUE THREAD

**Issue by lnevay** [pylhc/sdds#51]
### Documentation

- [X] Yes

### Operating System

macOS Big Sur 11.6.8

### Python Version

Python 3.9.13

### Package Version

cloned today

### Bug Description

When reading a file, the reader fails to parse the header. The type_hints dictionary in classes.py line 118 appears to only have the type hints from the base class and not this derived class, so it fails with:
```
Traceback (most recent call last):
  File "/Users/nevay/physics/reps/sdds/sdds/reader.py", line 40, in read_sdds
    version, definition_list, description, data = _read_header(inbytes)
  File "/Users/nevay/physics/reps/sdds/sdds/reader.py", line 61, in _read_header
    definitions.append({
  File "/Users/nevay/physics/reps/sdds/sdds/classes.py", line 118, in __init__
    type_hint = type_hints[argname]
KeyError: 'description'
```
See attached screenshot of debugging in pycharm.
<img width="1751" alt="Screenshot 2022-09-14 at 11 19 15" src="https://user-images.githubusercontent.com/9283103/190129426-b8cd6066-07a4-49d7-beb6-447ef9768049.png">

This doesn't seem to be specific to the data file and happens every time for me.

Cheers,
Laurie

### Steps to Reproduce

Load a file as per the documentation.

**Comment by JoschD** [comment]
Hey Laurie,

thank you very much for your bug-report.
We tried everything to reproduce your bug, but sadly (or luckily?) we can't.
Can you try creating a new python environment, `python -m pip install  -e .[test]` and run

```python
import sdds

sdds_data = sdds.read_sdds("sdds/tests/inputs/test_file.sdds")
print(sdds_data)
```
to see if that also fails? 
And also `pytest` to see if all the tests succeed?

If this runs I would assume you might have installed some outdated packages in your current env?

**Comment by lnevay** [comment]
Hello Josch,

Thanks for looking!  Yes, from what I can see it's just in the system library.  I'll try elsewhere / another system and as you suggest.  Sorry, few things to tend to in the last few days.

Cheers!
Laurie

On 14 Sep 2022, at 15:43, JoschD ***@***.******@***.***>> wrote:



Hey Laurie,

thank you very much for your bug-report.
We tried everything to reproduce your bug, but sadly (or luckily?) we can't.
Can you try creating a new python environment, python -m pip install -e .[test] and run

import sdds

sdds_data = sdds.read_sdds("sdds/tests/inputs/test_file.sdds")
print(sdds_data)

to see if that also fails?
And also pytest to see if all the tests succeed?

If this runs I would assume you might have installed some outdated packages in your current env?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpylhc%2Fsdds%2Fissues%2F51%23issuecomment-1246874858&data=05%7C01%7Claurie.nevay%40rhul.ac.uk%7Cea3d38d8b65e4c7109ca08da965f7fda%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C637987634149547147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8lGFBNHnE5vHq9VFLeuyvv7UFsEE9C69Oar%2B7IcUZGE%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACG2MH3DZP2ZEJ5UFUBO5XDV6HQBJANCNFSM6AAAAAAQMIRKOA&data=05%7C01%7Claurie.nevay%40rhul.ac.uk%7Cea3d38d8b65e4c7109ca08da965f7fda%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C637987634149703329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m3KLUEFJljn%2BuAfz9IBC%2F4mPO8OpPIMHd2WFJRGv1ck%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


This email, its contents and any attachments are intended solely for the addressee and may contain confidential information. In certain circumstances, it may also be subject to legal privilege. Any unauthorised use, disclosure, or copying is not permitted. If you have received this email in error, please notify us and immediately and permanently delete it. Any views or opinions expressed in personal emails are solely those of the author and do not necessarily represent those of Royal Holloway, University of London. It is your responsibility to ensure that this email and any attachments are virus free.
