### ISSUE TITLE
[Question]: Why not use the python sdds package ANL? 

### ISSUE THREAD

**Issue by Dronakurl** [pylhc/sdds#60]
### Documentation

- [X] Yes

### Question

There is this other sdds package here:
[www.aps.anl.gov/](https://www.aps.anl.gov/Accelerator-Operations-Physics/Software#Python%20SDDS%20Binaries)
Are there reasons not to use this? What are the main differences? It would be helpful to point that out on the `README` page.
When using elegant, you have to use their package and someone might confuse the packages, since the other package is also called `sdds`.

**Comment by JoschD** [comment]
I think the main reason was, that we wanted to have a lightweight pure-python PYPI available package that runs easily on all machines. There is a lot of history involved I guess, as this package was in earlier times a simple module of our code-collection, before we decided to compartmentalize more to get better maintainability and also to be able to share these modules easier with out colleagues.

As far as I remember, we looked at the "official" sdds package and decided it's too much hassle to install (and you need to register as well?).

**Comment by Dronakurl** [comment]
Thanks for clarifying. So the reasons are practical, but not in terms of functionality.
Just a few thoughts.
- You do not need to register. You only need a valid e-mail address for a code. I think, it is only a guard against too many requests on the server.
- The installation: Yes, that's awful. No pip, no venv. On windows, it is just installed somewhere (you figure out, where). Then you have to teach your environment where to find it
- I had a brief look at the code. It is part of a huge package of sdds tools, but I think the parts needed for the functionality of sdds can be isolated.
- pure-python: No, it's C. For parsing, that's not a bad idea to get better performance
- It is open source, too. So it should be allowed to arrange a closed package out of it. Did anyone try it?

**Comment by fsoubelet** [comment]
Hi again,

We have not tried extracting the relevant parts of this package, and we were mostly interested in making our existing implementation into its own, python-only package.
