### ISSUE TITLE
[Question]: The field 'format' in class Definition may be wrong?

### ISSUE THREAD

**Issue by mulingLHY** [pylhc/sdds#62]
### Documentation

- [X] Yes

### Question

I'm encountering an error while using this library to read SDDS5 files, meaning "class Definition does not have a field named format_string." I checked the 1995 documentation (version [1.4]) [https://doi.org/10.2172/179270](https://doi.org/10.2172/179270) on page 5, where the Definition only includes `format_string` without `format`.
I want to know where the field `format` in the Definition class comes from.

Recently, while using this library for SDDS5, I found that both reading and writing data were not implemented, so I made some additions. However, due to my limited understanding of the version history of SDDS, I cannot guarantee the completeness of my modifications. Can I submit these relevant changes? Alternatively, is there an updated version of this project available?

**Comment by JoschD** [comment]
Hello @mulingLHY,
thank you very much for your message. 
Sadly I have no idea what a SDDS5 file is and how it compares to "normal" SDDS files.
Your error sounds like a python error though, which is trying to convert a Definition field to a string.

Maybe you could provide a minimal (not-)working example including one of your SDDS5 files?
Then we can have a look and see what it going wrong.

Cheers,

Josch

**Comment by mulingLHY** [comment]
> Hello @mulingLHY, thank you very much for your message. Sadly I have no idea what a SDDS5 file is and how it compares to "normal" SDDS files. Your error sounds like a python error though, which is trying to convert a Definition field to a string.
> 
> Maybe you could provide a minimal (not-)working example including one of your SDDS5 files? Then we can have a look and see what it going wrong.
> 
> Cheers,
> 
> Josch

Sorry, my expression may be a little confused.
SDDS5 is the version of SDDS, current master branch is only compatible with SDDS1, while SDDS5 is not very different from SDDS1.
`reader.py line 113`
```python
def _read_header(
    inbytes: IO[bytes],
) -> Tuple[str, List[Definition], Optional[Description], Data]:
    word_gen = _gen_words(inbytes)
    version = next(word_gen)  # First token is the SDDS version
    assert version == "SDDS1", "This module is compatible with SDDS v1 only... are there really other versions?"
```

My question is that in the protocol of SDDS, I can only find `format_string` in the [Parameter Definition](https://ops.aps.anl.gov/manuals/SDDStoolkit/SDDStoolkitsu2.html#:~:text=units%C2%A0%3D%C2%A0NULL%20%C2%A0%0A%C2%A0%C2%A0%C2%A0%C2%A0STRING%C2%A0description%C2%A0%3D%C2%A0NULL%20%C2%A0%0A%C2%A0%C2%A0%C2%A0%C2%A0STRING-,format_string,-%3D%C2%A0NULL%20%C2%A0%0A%C2%A0%C2%A0%C2%A0%C2%A0STRING%C2%A0type%C2%A0%3D%C2%A0NULL%20%C2%A0%0A%C2%A0%C2%A0%C2%A0%C2%A0STRING%C2%A0fixed_value). 
But in class `Definition`, there is no field `format_string`. Is it a bug, or in SDDS1, the `format_string` is called `format` 
`classed.py line 99`
```python
class Definition:
    """
    Abstract class for the common behaviour of the data definition commands.


    The Column, Array and Parameter definitions inherit from this class. They can be created just by
    passing name and type and optionally more parameters that depend on the actual definition type.

    Fields:
        name (str): Name of the data.
        type (str): Type of the data.
                    One of "short", "long", "float", "double", "character", or "string".
        symbol (str): Optional. Allows specification of a symbol to represent the parameter;
                      it may contain escape sequences, for example,
                      to produce Greek or mathematical characters.
        units (str): Optional. Allows specification of the units of the parameter.
        description (str): Optional.  Provides for an informal description of the parameter.
        format (str): Optional. Specification of the print format string to be used to print the data
                      (e.g. for ASCII in SDDS or other formats). NOT IMPLEMENTED!

    """

    name: str
    type: str
    symbol: Optional[str] = None
    units: Optional[str] = None
    description: Optional[str] = None
    format: Optional[str] = None
```

**Comment by JoschD** [comment]
Hello again,

I see what you mean and you are right, `format` in our code should probably be called `format_string` as also the doc in the python code for that parameter is the same as the one in the sdds-documentation.

I think from our side, no one has ever used this parameter in the past, and hence it was not noticed. (also hence the " NOT IMPLEMENTED!" comment). But I see how this might cause issues when reading a file that has this field set.

I'll change this real quick and you can maybe test if works :)

Cheers,

Josch

**Comment by mulingLHY** [comment]
> Hello again,
> 
> I see what you mean and you are right, `format` in our code should probably be called `format_string` as also the doc in the python code for that parameter is the same as the one in the sdds-documentation.
> 
> I think from our side, no one has ever used this parameter in the past, and hence it was not noticed. (also hence the " NOT IMPLEMENTED!" comment). But I see how this might cause issues when reading a file that has this field set.
> 
> I'll change this real quick and you can maybe test if works :)
> 
> Cheers,
> 
> Josch

The reading and writing of column data both are not implemented, I think it's strange for such a project.  : -

**Comment by JoschD** [comment]
Hey, I made a PR. Is it possible for you to checkout that branch and test if it fixes your problem?

**Comment by mulingLHY** [comment]
> Hey, I made a PR. Is it possible for you to checkout that branch and test if it fixes your problem?
> 
> I am not sure if something crashes or just not reads the data or when you implement you own reading part it conflicts....
> 
> If you would like to see the reading/writing of the columns being implemented, and it sounds like you have already done that, maybe you could push your code to a repo and we can merge it.

Thanks, it works well

**Comment by fsoubelet** [comment]
@mulingLHY We're releasing a version today that should fix the error you've encountered. If you feel like submitting a PR with your changes regarding reading and writing data we'd be happy to take a look at it.
